In [3]:
# Q-1: Create an array [10,20,30,40,50,60,70,80,90].

# ->Get the first element.

# ->Get the last element.

# ->Get the 4th element.

# ->Get elements at positions [0,3,5].

import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90])
first = arr[0]
last = arr[-1]
fourth = arr[3]
position = arr[[0,3,5]]
print("First element :", first)
print("Last element :", last)
print("Fourth element :", fourth)
print("Elements at positions [0,3,5] :", position)

First element : 10
Last element : 90
Fourth element : 40
Elements at positions [0,3,5] : [10 40 60]


In [4]:
# Q-2: Reverse the above array.

reversed_arr = arr[::-1]
print(reversed_arr)

[90 80 70 60 50 40 30 20 10]


In [5]:
# Q-3: Replace the 2nd and 3rd elements with [999,888].

arr[1:3] = [999, 888]
print(arr)

[ 10 999 888  40  50  60  70  80  90]


In [6]:
# Q-4:Get element in 2nd row, 3rd column.
# Q-5:Get element in last row, last column.
# Q-6:Get the first column only.
# Q-7:Get the last row only.
# Q-8:Replace the value at position (1,1) with 999.

arr=[[11,12,13],
      [21,22,23],
      [31,32,33],
      [41,42,43]]

element = arr[1][2]
print("Element in 2nd row, 3rd column :", element)

last = arr[-1][-1]
print("Element in last row, last column :", last)

first_column = [row[0] for row in arr]
print("First column only :", first_column)

last_row = arr[-1]
print("Last row only :", last_row)

arr[1][1] = 999
print("Array after replacing value at position (1,1) with 999 :" ,arr)

Element in 2nd row, 3rd column : 23
Element in last row, last column : 43
First column only : [11, 21, 31, 41]
Last row only : [41, 42, 43]
Array after replacing value at position (1,1) with 999 : [[11, 12, 13], [21, 999, 23], [31, 32, 33], [41, 42, 43]]


In [10]:
# <!-- Slicing 1D -->


# Q-9:From [5,10,15,20,25,30,35,40]:

# ->Extract [10,15,20].

# ->Extract [5,15,25,35].

# ->Extract every second element.

# ->Extract elements from index 2 till end.

arr = np.array([5,10,15,20,25,30,35,40])
extract1 = arr[1:4]
extract2 = arr[::2]
extract3 = arr[2:]

print("Extracted 10, 15, 20 :", extract1)
print("Extracted 5,15,25,35 :", extract2)
print("Extracted every second element :", extract2)
print("Extracted elements from index 2 till end :", extract3)

Extracted 10, 15, 20 : [10 15 20]
Extracted 5,15,25,35 : [ 5 15 25 35]
Extracted every second element : [ 5 15 25 35]
Extracted elements from index 2 till end : [15 20 25 30 35 40]


In [14]:
# <!-- Slicing 2D -->

arr=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]


# Q-10:Extract first 2 rows and first 2 columns.

# Q-11:Extract last 2 rows and last 2 columns.

# Q-12:Extract the middle 2*2 submatrix (,7,10,11).

# Q-13:Extract all rows but only the 3rd column.

# Q-14:Extract all columns but only the 2nd row.

# Q-15:Reverse the order of rows.

# Q-16:Reverse the order of columns.

arr_np = np.array(arr)
extract_10 = arr_np[0:2, 0:2]
extract_last = arr_np[2:4, 2:4]
extract_middle = arr_np[1:3, 1:3]
extract_3d = arr_np[:, 2]
extract_2r = arr_np[1:2, :]
reverse_rows = arr_np[::-1, :]
reverse_cols = arr_np[:, ::-1]
print("Extracted first 2 rows and first 2 columns :", extract_10)
print("Extracted last 2 rows and last 2 columns :", extract_last)
print("Extracted middle 2x2 submetrix :", extract_middle)
print("Extracted all rows but only 3rd column :", extract_3d)
print("Extracted all columns 2nd row :", extract_2r)
print("Reverse order of rows :", reverse_rows)
print("Reverse order of columns :", reverse_cols)

Extracted first 2 rows and first 2 columns : [[1 2]
 [5 6]]
Extracted last 2 rows and last 2 columns : [[11 12]
 [15 16]]
Extracted middle 2x2 submetrix : [[ 6  7]
 [10 11]]
Extracted all rows but only 3rd column : [ 3  7 11 15]
Extracted all columns 2nd row : [[5 6 7 8]]
Reverse order of rows : [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reverse order of columns : [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [15]:
# <!-- Boolean Indexing -->

# Q-17:From [10,15,20,25,30,35,40]:

# ->Extract all values greater than 20.

# ->Extract even numbers.

# ->Extract numbers divisible by 5 but less than 30.

arr = np.array([10,15,20,25,30,35,40])
greater_than_20 = arr[arr > 20]
even_numbers = arr[arr % 2 == 0]
divisable = arr[arr % 5 == 0][arr < 30]
print("Values grater than 20 :", greater_than_20)
print("Even numbers :", even_numbers)
print("Numbers divisable by 5 but less than 30 :", divisable)

Values grater than 20 : [25 30 35 40]
Even numbers : [10 20 30 40]
Numbers divisable by 5 but less than 30 : [10 15 20 25]


In [16]:
# Q-18:Replace all odd numbers with -1 in [1,2,3,4,5,6,7,8,9].
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr % 2 !=0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [17]:
# Q-19:From a 2D array,extract all values greater than 10.
arr_2d = np.array([[5,12,7], [15,8,20], [3,9,11]])
greater_10 = arr_2d[arr_2d > 10]
print(greater_10)

[12 15 20 11]
