In [2]:
# Q-1: Create a 1D NumPy array of numbers 0-9.

# ->Iterate using a normal for loop and print each element.

# ->Then multiply each element by 2 using a loop, not vectorized.

import numpy as np

arr = np.arange(10)
print(arr)

for i in range(len(arr)):
    print(arr[i])

for i in range(len(arr)):
    arr[i] = arr[i] * 2

print(arr)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9
[ 0  2  4  6  8 10 12 14 16 18]


In [3]:
# Q-2: Create a 2D array of shape(3,4) with values 0-11.

# ->Print each rows separately.

# ->Print all elements using nested loops.

# ->Flatten the array and iterate as a 1D array.

arr2d = np.arange(12).reshape(3, 4)
print(arr2d)

for row in arr2d:
    print(row)
for i in range(arr2d.shape[0]):
    for j in range(arr2d.shape[1]):
        print(arr2d[i][j])

flat = arr2d.flatten()
for elements in flat:
    print(elements)

print(flat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# Q-3: Create a (2,3) array with values 10-15.

# ->Iterate over all elements using np.nditer.

# ->Modify the array in-place so that each element become its square.

# ->Iterate in column-major(fortran)order.

arr = np.arange(10, 16).reshape(2, 3)
print(arr)

for it in np.nditer(arr):
    print(it)

for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] = x * x
    print(arr)


[[10 11 12]
 [13 14 15]]
10
11
12
13
14
15
[[100  11  12]
 [ 13  14  15]]
[[100 121  12]
 [ 13  14  15]]
[[100 121 144]
 [ 13  14  15]]
[[100 121 144]
 [169  14  15]]
[[100 121 144]
 [169 196  15]]
[[100 121 144]
 [169 196 225]]


In [5]:
# Q-4: Given Two arrays:

# a=np.array([1,2,3])
# b=np.array([[10],[20],[30]])

# ->Use np.nditer([a,b]) to print their sum element wise.

# ->Check how broadcasting works.

a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

for x, y in np.nditer([a,b]):
    print(x, '+', y, '=', x+y)

1 + 10 = 11
2 + 10 = 12
3 + 10 = 13
1 + 20 = 21
2 + 20 = 22
3 + 20 = 23
1 + 30 = 31
2 + 30 = 32
3 + 30 = 33


In [6]:
# Q-5: Create a 2D array of shape(3,3) with values 1-9.

# ->Use np.ndenumerate to print index and value of each element.

# ->Replace all elements at even row indices with 0.
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

for index, value in np.ndenumerate(arr):
    if index[0] % 2 == 0:
        arr[index] = 0

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9
[[0 0 0]
 [4 5 6]
 [0 0 0]]


In [7]:
# Q-6: Create a (2,2,3) array using np.arange(12).

# ->Iterate block by block(normal loops).

# ->Iterate element by element using np.nditer.

# ->Use np.ndenumerate to print(i,j,k) index with its value.

arr = np.arange(12).reshape(2, 2, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [10]:
# Q-7:Suppose you have a grayscale image of shape(4,4) with values 0-255.

# ->Use np.nditer to set all values<128-->0 and all values>=128-->255.

# ->Iterate with np.ndenumerate and print the coordinates of all white pixels(255).

img = np.random.randint(0, 256,(4, 4))
print("Original:\n", img)

for x in np.nditer(img, op_flags = ['readwrite']):
    x[...] = 0 if x[...] < 128 else 255
print("Processed\n", img)

print("White pixels coordinates:")

for idx, val in np.ndenumerate(img):
    if val == 255:
        print(idx)

Original:
 [[185 203 209 203]
 [  5 153   3 112]
 [234  50 240 165]
 [143  16  37 248]]
Processed
 [[255 255 255 255]
 [  0 255   0   0]
 [255   0 255 255]
 [255   0   0 255]]
White pixels coordinates:
(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 1)
(2, 0)
(2, 2)
(2, 3)
(3, 0)
(3, 3)
