In [2]:
# Q-1: Create a 1D NumPy array of size 10.

# ->Find its shape,ndim and size.

import numpy as np

arr = np.arange(10)
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimentions:", arr.ndim)
print("Size:", arr.size)

Array: [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Dimentions: 1
Size: 10


In [3]:
# Q-2: Make a 2D array of shape(3,4) with values from 0 to 11.

# ->Print its shape,ndim and size.

arr_2d = np.arange(12).reshape(3, 4)
print(arr_2d)
print("Shape", arr_2d.shape)
print("Dimentions:", arr_2d.ndim)
print("Size:", arr_2d.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape (3, 4)
Dimentions: 2
Size: 12


In [4]:
# Q-3: Convert a 1D array of size 12 into:

# ->shape(3,4)

# ->shape(2,2,3)

# ->shape(6,2)

arr_1d = np.arange(12).reshape(3, 4)
print("Shape:", arr_1d.shape)
print(arr_1d)

arr_2d = arr_1d.reshape(2, 2, 3)
print("Shape:", arr_2d.shape)
print(arr_2d)

arr_3d = arr_1d.reshape(6, 2)
print("Shape:", arr_3d.shape)
print(arr_3d)


Shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (6, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [5]:
# Q-4: Use -1 in reshape to automatically calculate the missing dimension. Example reshape(3,4) into (2,-1)

a1d = np.arange(12).reshape(3, 4)
print(a1d)
print(a1d.reshape(2, -1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [6]:
# Q-5: Create a 2D array of shape (3,3) and:

# ->Flatten it into 1D using flatten()

# ->Convert it into 1D using ravel() and change one element.

# ->Check whether original array changes or not.

arr_2d = np.arange(9).reshape(3, 3)
print("Original array:", arr_2d)
arr_f = arr_2d.flatten()
print("Flattened:", arr_f)

arr_r = arr_2d.ravel()
print("Raveled:", arr_r)

arr_r[0] = 99
print("Modified raveled:", arr_r)
print(arr_2d)

Original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Flattened: [0 1 2 3 4 5 6 7 8]
Raveled: [0 1 2 3 4 5 6 7 8]
Modified raveled: [99  1  2  3  4  5  6  7  8]
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [7]:
# Q-6 Take a 1D array [1,2,3,4]

# ->Convert it into shape(1,4) using np.newaxis

# ->Convert it into shape(4,1) using np.expand_dims

arr = np.array([1, 2, 3, 4])
arr_row = arr[np.newaxis, :]
arr_col = (np.expand_dims(arr, axis=1).shape)
arr_co = (np.expand_dims(arr, axis=0).shape)
print("Original array:", arr)
print("Row vector:", arr_row)
print("Row:", arr_co)
print("Column:", arr_col)

Original array: [1 2 3 4]
Row vector: [[1 2 3 4]]
Row: (1, 4)
Column: (4, 1)


In [8]:
# Q-7: Create an array of shape(1,5,1) and remove all extra dimensions using squeeze().

arr = np.arange(5).reshape(1, 5, 1)
arr_squeezed = arr.squeeze()
print("Original array:", arr)
print("Squeeze:", arr_squeezed)

Original array: [[[0]
  [1]
  [2]
  [3]
  [4]]]
Squeeze: [0 1 2 3 4]


In [9]:
# -8: Make a 2D array of shape(2,3) and print its transpose.

# ->Verify shape before and after transpose.

arr_2d = np.arange(6).reshape(2, 3)
print("Original:", arr_2d)
print("Shape:", arr_2d.shape)

arr_trans = arr_2d.T
print("Transpose:", arr_trans)
print("Shape of transpose:", arr_trans.shape)

Original: [[0 1 2]
 [3 4 5]]
Shape: (2, 3)
Transpose: [[0 3]
 [1 4]
 [2 5]]
Shape of transpose: (3, 2)


In [10]:
# Q-9: Create a 3D array of shape (2,3,4) and use transpose() to swap axes.

# ->Try arr.transpose(1,0,2) and check new shape.

arr_3d = np.arange(24).reshape(2, 3, 4)
print("Original array:", arr_3d)

arr_transposed = arr_3d.transpose(1, 0, 2)
print("Transposed:", arr_transposed)
print("New shape:", arr_transposed.shape)

Original array: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Transposed: [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
New shape: (3, 2, 4)


In [11]:
# Q-10: Suppose you have 100 images stored in an array with shape(100,28,28) (100 grayscale images of 28*28).

# ->Reshape this into (100,784) (flatten each image into 1D of 784 pixels.)

# ->Then again reshape one image back to (28,28)

images = np.arange(100 * 28* 28).reshape(100, 28, 28)
images_reshaped = images.reshape(100, 784)
one_img = images_reshaped[0].reshape(28, 28)

print(images)
print(images_reshaped)
print(one_img.shape)


[[[    0     1     2 ...    25    26    27]
  [   28    29    30 ...    53    54    55]
  [   56    57    58 ...    81    82    83]
  ...
  [  700   701   702 ...   725   726   727]
  [  728   729   730 ...   753   754   755]
  [  756   757   758 ...   781   782   783]]

 [[  784   785   786 ...   809   810   811]
  [  812   813   814 ...   837   838   839]
  [  840   841   842 ...   865   866   867]
  ...
  [ 1484  1485  1486 ...  1509  1510  1511]
  [ 1512  1513  1514 ...  1537  1538  1539]
  [ 1540  1541  1542 ...  1565  1566  1567]]

 [[ 1568  1569  1570 ...  1593  1594  1595]
  [ 1596  1597  1598 ...  1621  1622  1623]
  [ 1624  1625  1626 ...  1649  1650  1651]
  ...
  [ 2268  2269  2270 ...  2293  2294  2295]
  [ 2296  2297  2298 ...  2321  2322  2323]
  [ 2324  2325  2326 ...  2349  2350  2351]]

 ...

 [[76048 76049 76050 ... 76073 76074 76075]
  [76076 76077 76078 ... 76101 76102 76103]
  [76104 76105 76106 ... 76129 76130 76131]
  ...
  [76748 76749 76750 ... 76773 76774 767

In [12]:
# Q-11:You have a dataset with 1000 rows (samples) and 10 features->shape(1000,10).

# (a) Find its ndim,size and shape.

# (b) Reshape it into (10,1000) and observe the diffrence.

# (c) Extract a single feature as a 1D vector (1000,).

# (d) Extract a single feature as a column vector (1000,1).

arr = np.arange(10000).reshape(1000, 10)
print(arr.ndim)
print(arr.size)
print(arr.shape)

arr_reshaped = arr.reshape(10, 1000)
print(arr_reshaped.shape)

f_1d = arr[:, 0]
print(f_1d.shape)



2
10000
(1000, 10)
(10, 1000)
(1000,)


In [16]:
# Q-13:An RGB image has shape(64,64,3)->(height,width,channels).

# (a)Reshape it into (4096,3) so each pixels RGB is a row.

# (b) Suppose you have 100 images->shape(100,64,64,3).

# ->Reshape into (100,12288) for feeding into a neural network.

# ->Transpose a single image into (3,64,64) (channel-first format for PyTorch).

image = np.random.randint(0, 256, (64, 64, 3), dtype=np.uint8)
image_reshaped = image.reshape(4096, 3)
print(image)
print(image.ndim)
print("Reshaped image:", image_reshaped.shape)

image = np.random.randint(0, 256, (100, 64, 64, 3), dtype=np.uint8)
images_reshaped = image.reshape(100, 12288)
print(image.ndim)
print("Reshped images:", images_reshaped.shape)

image_transpose = image[0].transpose(2, 0, 1)
print("Transposed image:", image_transpose.shape)
print(image_transpose)

[[[ 40  35  75]
  [197  40 229]
  [239 117  32]
  ...
  [ 31 189  26]
  [240  13 190]
  [ 59 162 230]]

 [[185 252 123]
  [ 99  34 151]
  [103  81 240]
  ...
  [245   6 120]
  [202 117 235]
  [110  30 151]]

 [[251  61 180]
  [ 27 197 187]
  [ 41 228  50]
  ...
  [220 123 202]
  [255 132 205]
  [  6 174  22]]

 ...

 [[ 19 248 209]
  [ 75 254  50]
  [ 49 103  39]
  ...
  [137 202  46]
  [ 45  13 232]
  [181 108 171]]

 [[ 31 253 220]
  [ 75 216  57]
  [237 226 154]
  ...
  [132 201  90]
  [155  72  61]
  [144  32 145]]

 [[ 51 145 240]
  [118 148  81]
  [ 86  27  94]
  ...
  [168  43 230]
  [ 87 237 105]
  [ 98  20  42]]]
3
Reshaped image: (4096, 3)
4
Reshped images: (100, 12288)
Transposed image: (3, 64, 64)
[[[186 162 193 ... 210 254  77]
  [175 140 232 ... 113  43 203]
  [ 40 143 231 ...  46 185  82]
  ...
  [253 185 250 ...  60  21 134]
  [ 80   5  54 ...  56 197 229]
  [219 130 219 ...  79 157 123]]

 [[216 147 247 ...  35  18  25]
  [204 245 116 ... 170  77 191]
  [213 240  75 ..

In [19]:
# Q-14:A dataset has shape(10000,20) (10,000 samples,20 features).

# (a)Reshape it into (100,100,20)->100 batches,each with 100 samples.

# (b)Select one batch(100,20) and transpose it into (20,100).

data = np.random.rand(10000, 20)
data_batches = data.reshape(100, 100, 20)
print("Reshaped data:", data_batches.shape)

# A
batch = data_batches[0]
print(batch.shape)

batch_transposed = batch.T
print(batch_transposed.shape)



Reshaped data: (100, 100, 20)
(100, 20)
(20, 100)


In [20]:
# Q-15:You have daily sensor data with shape(365,24)->365 days 24 hourly readings each day.

# (a)Flatten it into (8760,).

# (b)Add an extra dimension to make (365,24,1) for ML input.

# (c)Use sequeeze to bring it back to (365,24).

sensor_data = np.random.rand(365, 24)

# a
flattened = sensor_data.flatten()
print("Flatten shape:", flattened.shape)

# b
sensor_expanded = sensor_data[..., np.newaxis]
print("Expanded shape:", sensor_expanded.shape)

# c
sensor_squeezed = sensor_expanded.squeeze()
print("Squeezed shape:", sensor_squeezed.shape)

Flatten shape: (8760,)
Expanded shape: (365, 24, 1)
Squeezed shape: (365, 24)


In [22]:
# Q-16: You have stock prices with shape(30,5)->30 days, 5 companies.

# (a)Extract one company's stock price as a 1D array(30,).

# (b)Convert the same into a column vector (30,1).

# (c)Transpose the dataset to (5,30)->stocks*days.

stock_prices= np.random.rand(30, 5)
company_1d = stock_prices[:, 0]
company_col = company_1d.reshape(-1, 1)
stock_transposed = stock_prices.T

print("Company 1d shape:", company_1d.shape)
print("Company column shape:", company_col.shape)
print("Transpose shape:", stock_transposed.shape)
print(stock_transposed)
print(stock_prices.shape)

Company 1d shape: (30,)
Company column shape: (30, 1)
Transpose shape: (5, 30)
[[0.03769214 0.72039355 0.28978282 0.83157456 0.85991209 0.73030427
  0.49753103 0.86800284 0.65015135 0.12653515 0.24834956 0.25200036
  0.85021626 0.10690067 0.02834627 0.97744553 0.75742268 0.91510025
  0.5097096  0.39112386 0.04001932 0.28963464 0.72035722 0.67422244
  0.70210471 0.21258122 0.67736536 0.69709079 0.2928913  0.78833069]
 [0.00148143 0.21896367 0.84087842 0.106892   0.83384649 0.20411269
  0.51575969 0.64818168 0.75300922 0.726509   0.62551372 0.59092143
  0.60654382 0.34414674 0.48527277 0.81355128 0.99662133 0.88616274
  0.9632345  0.54121725 0.80107251 0.85535919 0.79571265 0.26553652
  0.03103401 0.61048362 0.66390248 0.30257336 0.63518167 0.79283223]
 [0.02235334 0.54661345 0.75493449 0.08743572 0.00205083 0.19922499
  0.63364077 0.85703045 0.47857231 0.9674454  0.40622792 0.82292682
  0.35795475 0.50760626 0.88955662 0.54408564 0.63978837 0.48882403
  0.02740263 0.81967575 0.44476283 

In [24]:
# Q-17:You have 1000 grayscale images of shape(1000,28,28).

# (a)Reshape into (1000,28,28,1)->channel-last format(Tensorflow/Keras).

# (b)Reshape into (1000,1,28,28)->channel-first format(PyTorch).

# (c)Squeeze back into (1000,28,28).

images = np.random.rand(1000, 28, 28)
images_channel_last = images.reshape(1000, 28, 28, 1)
images_channel_first = images.reshape(1000, 1, 28, 28)
images_squeezed = images_channel_last.squeeze()

print("Channel last shape:", images_channel_last.shape)
print("Channel first shape:", images_channel_first.shape)
print("Squeezed shape:", images_squeezed.shape)
# print(images_channel_first)
# print(images_channel_last)
# print(images_squeezed)
# print(images)

Channel last shape: (1000, 28, 28, 1)
Channel first shape: (1000, 1, 28, 28)
Squeezed shape: (1000, 28, 28)


In [25]:
# Q-18:You have 200 senetences,each represented by 50 words,each word embedding of 100 dimensions.

# ->shape(200,50,100)

# (a)Flatten each sentence into (200,5000) for a bag-of-word style model.

# (b)Transpose it to (200,100,50) so embeddings come before word positions.

# (c)Extract one sentence and reshape into (50,100)again.

senetences = np.random.rand(200, 50, 100)

# a
flattened_sen = senetences.reshape(200, 5000)
print("Flattened shape:", flattened_sen.shape)

# b
transposed_sen = senetences.transpose(0, 2, 1)
print("Transposed shape:", transposed_sen.shape)

# c
one_senetences = senetences[0].reshape(50, 100)
print("One senetence shape:", one_senetences.shape)
print(one_senetences)

Flattened shape: (200, 5000)
Transposed shape: (200, 100, 50)
One senetence shape: (50, 100)
[[0.38683315 0.10618088 0.52571928 ... 0.99950853 0.75461082 0.38216419]
 [0.0365471  0.25135868 0.93744163 ... 0.46763374 0.15197816 0.40633383]
 [0.36254019 0.35673027 0.29240501 ... 0.55660939 0.80604953 0.27996054]
 ...
 [0.36619859 0.22252575 0.45189588 ... 0.43287382 0.33393872 0.62855191]
 [0.73020522 0.49228405 0.95491934 ... 0.80965615 0.41171542 0.99681459]
 [0.23991169 0.39158523 0.90481337 ... 0.73765499 0.92807035 0.27702181]]


In [29]:
# TASK SET 1: Shape & Reshape

# Task 1

# Create a 1D NumPy array of numbers 1 to 12 and:

# Print its shape

# Reshape it into (3,4)

# Print the new shape

import numpy as np

arr = np.arange(0, 12)
print(arr.shape)

arr_reshape = arr.reshape(3, 4)
print(arr_reshape.reshape)
print(arr_reshape.shape)


# Task 2

# Create a 2D array of shape (2,6) and:

# Convert it into a 1D array using reshape(-1)

# Print both arrays

arr_2d = np.arange(12).reshape(2, 6)
print("2D array:\n", arr_2d)
arr_1d = arr_2d.reshape(-1)
print("1d array:\n", arr_1d)

(12,)
<built-in method reshape of numpy.ndarray object at 0x000001B277265C50>
(3, 4)
2D array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
1d array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
# 🔹 TASK SET 2: Ravel vs Flatten
# Task 3

# Create this array:

# [[10, 20, 30],
#  [40, 50, 60]]


# Convert it into 1D using ravel()

# Convert it into 1D using flatten()

# Print both results

arr_2d = np.array([[10, 20, 30],[40, 50, 60]])
arr_ravel = arr_2d.ravel()
arr_flatten = arr_2d.flatten()

print("Ravel\n", arr_ravel)
print("Flatten\n", arr_flatten)


# Task 4

# Change the first value of the ravel output and observe:

# Does the original array change or not?

arr_ravel[0] = 99
print("Modified ravel\n", arr_ravel)
print(arr_2d)

Ravel
 [10 20 30 40 50 60]
Flatten
 [10 20 30 40 50 60]
Modified ravel
 [99 20 30 40 50 60]
[[99 20 30]
 [40 50 60]]


In [35]:
# TASK SET 3: Resize
# Task 5

# Create a NumPy array from 1 to 6 and:

# Resize it to (2,3)

# Print the array

arr = np.arange(1, 7)
arr_resized = arr.reshape(2, 3)
print(arr)
print(arr_resized)

# Task 6

# Resize the same array to (3,4) and observe:

# What values are added?

# arr_resized_2 = arr.reshape(3, 4)
# print(arr_resized_2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
