In [13]:
# Dataset 1 — Students Marks

# marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

# Q11: Find indexes of students who passed (marks ≥ 50).

# Q12: Replace all marks below 50 with 0 using np.where().

# Q13: Find where a new score 75 should be inserted to keep marks sorted.

# Q14: Get all scores greater than average marks.
import numpy as np

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])
avg = np.where(marks > 50)
print(avg)

rpl = np.where(marks<50, 0, marks)
print(rpl)

new = np.searchsorted(marks, 75)
print(new)

great = np.mean(marks)
greater = marks[marks>great]
print(great)
print(greater)

(array([2, 3, 5, 6, 7]),)
[ 0 50 65 80  0 90 55 70]
8
60.625
[65 80 90 70]


In [16]:
# 🧩 Dataset 2 — Product Prices

# prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

# Q15: Find positions of products cheaper than ₹1000.

# Q16: Replace prices above ₹2000 with 'Expensive', others with 'Affordable'.

# Q17: Using np.searchsorted(), find where ₹1600 should be inserted to maintain order.

# Q18: Get all product prices between ₹1000 and ₹2000 using boolean indexing.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])
cheap = np.where(prices>1000)
print(cheap)

pla = np.where(prices>2000, 'Expensive', 'Affordable')
print(pla)

price = np.searchsorted(prices, 1600)
print(price)

beet = np.where((prices>1000) & (prices<2000))
print(beet)

(array([0, 2, 3, 4, 6]),)
['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Affordable' 'Expensive']
3
(array([0, 2, 4]),)
