In [1]:
# Q-1:Create two 1D arrays [1,2,3] and [4,5,6].

# ->Join them using np.concatenate.

# ->Join them using np.hstack.

# ->What is the diffrence in output?
import numpy as np

arr1d = [1, 2, 3]
arr1d1 = [4, 5, 6]

result_concat = np.concatenate((arr1d, arr1d1))
result_hstack = np.hstack((arr1d, arr1d1))
print("Using np.concatenate:", result_concat)
print("Using np.hstack:", result_hstack)


Using np.concatenate: [1 2 3 4 5 6]
Using np.hstack: [1 2 3 4 5 6]


In [3]:
# Q-2:Given arrays:

# a=np.array([[1,2],[3,4]])
# b=np.array([[5,6],[7,8]])

# ->Join them row-wise using concatenate.

# ->Join them column-wise using concatenate.

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print("Row wise:", np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

Row wise: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# Q-3:Create two 1D arrays and join them into a 2D column matrix using np.column_stack.

arr = [1, 2, 3]
arr1d = [4, 5, 6]
result = np.column_stack((arr, arr1d))
print("Using np.column:", result)


Using np.column: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Q-4:Create arrays:

# a=np.array([1,2,3])
# b=np.array([4,5,6])

# ->Stack them using np.stack with axis=0

# ->Stack them using np.stack with axis=1

# ->Explain the diffrence in shape.

a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# Q-5:Create a (2,2) array filled with ones and another (2,2) array filled with zeros.

# ->Stack them along depth using np.dstack.

# ->Check the shape and explain.

ones = np.ones((2,2))
zeros = np.zeros((2,2))

result = np.dstack((ones, zeros))
print(result)
print(result.shape)

[[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]]
(2, 2, 2)


In [7]:
# Q-6:Create three arrays [10,20,30],[40,50,60],[0,80,90].

# ->Join them using np.vstack.

# ->Join them using np.row_stack.

# ->Are the results same?

arr1d = [10,20,30]
arr1d1 = [40,50,60]
arr1d2 = [0,80,90]
result_vstack = np.vstack((arr1d, arr1d1, arr1d2))
result_row_stack = np.hstack((arr1d, arr1d1, arr1d2))

print(result_vstack)
print(result_row_stack)

[[10 20 30]
 [40 50 60]
 [ 0 80 90]]
[10 20 30 40 50 60  0 80 90]


In [8]:
# Q-7:You have two features of students:

# age=np.array([18,19,20,21])
# marks=np.array([85,90,78,88])

# ->Combine them into a 2D dataset where each row is [age,marks].

age=np.array([18,19,20,21])
marks=np.array([85,90,78,88])
dataset = np.column_stack((age, marks))
print(dataset)

[[18 85]
 [19 90]
 [20 78]
 [21 88]]


In [10]:
# Q-8:You have 3 grayscale images of size (2,2):

# R=np.array([[255,0],[0,255]]) #red channel
# G=np.array([[0,255],[255,0]]) #green channel
# B=np.array([[100,100],[100,100]]) #blue channel


# ->Combine them into a single RGB image of shape(2,2,3) using np.dstack.

R=np.array([[255,0],[0,255]]) #red channel
G=np.array([[0,255],[255,0]]) #green channel
B=np.array([[100,100],[100,100]]) #blue channel

rgb_image = np.dstack((R,G,B))
print(rgb_image)
print(rgb_image.shape)

[[[255   0 100]
  [  0 255 100]]

 [[  0 255 100]
  [255   0 100]]]
(2, 2, 3)


In [13]:
# Q-9:You have two 1D arrays:

# city=np.array(['Delhi','Mumbai','Chennai'])
# temp=np.array([30,32,35])

# ->Use np.column_stack to combine them so that you get:

city=np.array(['Delhi','Mumbai','Chennai'])
temp=np.array([30,32,35])
result = np.column_stack((city, temp))
print(result)

[['Delhi' '30']
 ['Mumbai' '32']
 ['Chennai' '35']]


In [15]:
# Q-1: You have a dataset of employee salaries(in thousands):

# salaries=np.array([
#     [101,45000,3],
#     [102,52000,4],
#     [103,58000,5],
#     [104,61000,6],
#     [105,70000,8],
#     [106,75000,9]
# ])

# Each row=[Employee_ID,Salary,Experience]

# Task: Split this dataset vertically into 3 columns(so you get ID,Salary and Experience seperately).

salaries=np.array([
    [101,45000,3],
    [102,52000,4],
    [103,58000,5],
    [104,61000,6],
    [105,70000,8],
    [106,75000,9]
])

emp_id, salary, experience = np.hsplit(salaries, 3)
print("Employee IDs:\n", emp_id)
print("Salaries:\n", salary)
print("Experience:\n", experience)

Employee IDs:
 [[101]
 [102]
 [103]
 [104]
 [105]
 [106]]
Salaries:
 [[45000]
 [52000]
 [58000]
 [61000]
 [70000]
 [75000]]
Experience:
 [[3]
 [4]
 [5]
 [6]
 [8]
 [9]]


In [ ]:
# Q-2: Monthly sales(in thousands) of two branches combined:

# sales=np.array([
#     [12,15,18,20,23,25],
#     [14,17,20,22,26,30]
# ])

# Task: Split the array horizontally into 2 equal halves.

# ->First half=Jan-Mar

# ->Second half=Apr-Jun

sales=np.array([
    [12,15,18,20,23,25],
    [14,17,20,22,26,30]
])
jan_mar, apr_jun = np.hsplit(sales, 2)
print("First half (Jan-Mar):\n", jan_mar)
print("Second half (Apr-Jun):\n", apr_jun)

First half (Jan-Mar):
 [[12 15 18]
 [14 17 20]]
Second half (Apr-Jun):
 [[20 23 25]
 [22 26 30]]


In [17]:
# Q-3: You have quarterly revenue data for 3 years:

# revenue=np.array([
#     [100,120,130,150],
#     [200,230,250,270],
#     [300,320,350,380]
# ])

# Task: Split this into 4 parts- each part represents one quarter (Q1,Q2,Q3,Q4).

revenue=np.array([
    [100,120,130,150],
    [200,230,250,270],
    [300,320,350,380]
])
q1, q2, q3, q4 = np.hsplit(revenue, 4)
print("Q1:\n", q1)
print("Q2:\n", q2)
print("Q3:\n", q3)
print("Q4:\n", q4)

Q1:
 [[100]
 [200]
 [300]]
Q2:
 [[120]
 [230]
 [320]]
Q3:
 [[130]
 [250]
 [350]]
Q4:
 [[150]
 [270]
 [380]]


In [18]:
# Q-4: marks=np.array([
#     [78,82,89,91],
#     [85,87,90,93],
#     [75,80,83,88],
#     [92,95,97,99]
# ])

# Each row=student
# Each column=subject

# Task: Split students into 2 equal groups(top half,bottom half).

marks=np.array([
    [78,82,89,91],
    [85,87,90,93],
    [75,80,83,88],
    [92,95,97,99]
])
top_half, bottom_half = np.vsplit(marks, 2)
print("Top half (first 2 students):\n", top_half)
print("Bottom half (last 2 students):\n", bottom_half)

Top half (first 2 students):
 [[78 82 89 91]
 [85 87 90 93]]
Bottom half (last 2 students):
 [[75 80 83 88]
 [92 95 97 99]]


In [19]:
# Q-5: data=np.array([
#     [[10,20],[30,40]],
#     [[50,60],[70,80]]
# ])

# Here Each depth represents 2 diffrent months(Jan and Feb).

# Task: Split this array along depth(axis=2)->so that you get 2 arrays,one for each month.

data=np.array([
    [[10,20],[30,40]],
    [[50,60],[70,80]]
])
jan, feb = np.dsplit(data, 2)
print("January data:\n", jan)
print("February data:\n", feb)

January data:
 [[[10]
  [30]]

 [[50]
  [70]]]
February data:
 [[[20]
  [40]]

 [[60]
  [80]]]


In [20]:
# Q-6: transactions=np.array([
#     [2000,2500,3000,3500,4000,4500],
#     [1800,2200,2700,3200,3700,4200]
# ])

# Each row->Account holder
# Each column->Month(Jan to Jun)

# Task-1: Split into 3 parts(each part=2 months).

# Task-2: Find total amount of each split part using np.sum()

transactions=np.array([
    [2000,2500,3000,3500,4000,4500],
    [1800,2200,2700,3200,3700,4200]
])
jan_feb, mar_apr, may_jun = np.hsplit(transactions, 3)
print("Jan-Feb:\n", jan_feb)
print("Mar-Apr:\n", mar_apr)
print("May-Jun:\n", may_jun)
print("Total for Jan-Feb:", np.sum(jan_feb))
print("Total for Mar-Apr:", np.sum(mar_apr))
print("Total for May-Jun:", np.sum(may_jun))

Jan-Feb:
 [[2000 2500]
 [1800 2200]]
Mar-Apr:
 [[3000 3500]
 [2700 3200]]
May-Jun:
 [[4000 4500]
 [3700 4200]]
Total for Jan-Feb: 8500
Total for Mar-Apr: 12400
Total for May-Jun: 16400


In [ ]:
# Q-7: feedback=np.array([
#     [4,5,3,4,2,5],
#     [5,4,4,5,3,4],
#     [3,4,2,3,4,5]
# ])

# Each row=Customer
# Each column=Rating given over 6 months

# Task: Split ratings into first 3 months and last 3 months.

# Then calculate average rating in both parts for each customer.

feedback=np.array([
    [4,5,3,4,2,5],
    [5,4,4,5,3,4],
    [3,4,2,3,4,5]
])

first_half, last_half = np.hsplit(feedback, 2)
print(first_half)
print(last_half)
print(np.mean(first_half, axis=1))
print(np.mean(last_half, axis=1))
print(np.mean(first_half))
print(np.mean(last_half))

[[4 5 3]
 [5 4 4]
 [3 4 2]]
[[4 2 5]
 [5 3 4]
 [3 4 5]]
[4.         4.33333333 3.        ]
[3.66666667 4.         4.        ]
3.7777777777777777
3.888888888888889


In [23]:
# Q-8: You have data from 4 sensors(rows),recorded every second (10 columns).

# sensor_data=np.random.randint(10,100,(4,10))


# Task: 
# 1.Split data into 5 equal time intervals(2 seconds each).

# 2.Find average value in each interval.

sensor = np.random.randint(10,100,(4,10))
interval1, interval2, interval3, interval4, interval5 = np.hsplit(sensor, 5)
print(np.mean(interval1))
print(np.mean(interval2))
print(np.mean(interval3))
print(np.mean(interval4))
print(np.mean(interval5))

42.75
47.0
52.75
63.0
42.25
