In [5]:
# Q-1: Create a 1D array with values [5,10,15,20,25].

# ->Print the array.

# ->Print its dimension and shape.

import numpy as np

arr1d = np.array([5,10,15,20,25])
print(arr1d)
print(arr1d.ndim)
print(arr1d.shape)

[ 5 10 15 20 25]
1
(5,)


In [2]:
# Q-2: Create a 1D array of numbers from 0 to 9.

# ->Verify that its 1D.

# ->Print its shape.

import numpy as np

arr1d = np.array(range(10))
print(arr1d)
print(arr1d.ndim)
print(arr1d.shape)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [3]:
# Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.

# ->Print the array.

# ->Print its ndim and shape.

arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [4]:
# Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.

# ->Print the array.

# ->Verify its Dimension and Shape.

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [5]:
# Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.

# ->Print the array.

# ->Print its shape and dimensions.

arr3d = np.array([[[1,2],[3,4],[5,6]]])
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[1 2]
  [3 4]
  [5 6]]]
3
(1, 3, 2)


In [6]:
# Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).

# ->Print the array.

# ->Print its dimension and shape.

arr3d = np.random.randint(1,20, size = (2,2,3))
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)

[[[16 12  3]
  [ 9 12 11]]

 [[14 16  5]
  [14 17 18]]]
3
(2, 2, 3)


In [7]:
# Q-7 Create 4D array with shape(1,2,2,3).

# ->Print the array.

# ->Print its shape and dimensions.

arr4d = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(arr4d)
print(arr4d.ndim)
print(arr4d.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
4
(1, 2, 2, 3)


In [9]:
# Q-1: Create a 2*3 array of zeros.Print dimension and shape.

import numpy as np

arr_zeros = np.zeros((2, 3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Q-2: Create a 3*4 array of ones(int type).

arr_ones = np.ones((3, 4), dtype=int)
print(arr_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
# Q-3: Create a 2*2 array filled with 9.

arr_full = np.full((2, 2), 9)
print(arr_full)

[[9 9]
 [9 9]]


In [12]:
# Q-4: Create an empty 2*3 array and print it.

arr_empty = np.empty((2, 3))
print(arr_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Q-5: Create a 1D array of numbers from 10 to 50 with step=5 using arange.

rang = np.arange(10, 51, 5)
print(rang)

[10 15 20 25 30 35 40 45 50]


In [16]:
# Q-6: Create 5 evenly spaced numbers between 0 and 2 using linespace.
linespace = np.linspace(0, 2, 5)
print(linespace)

[0.  0.5 1.  1.5 2. ]


In [17]:
# Q-7: Create a 4*4 identity matrix.

ident = np.eye(4)
print(ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Q-8: Given array b=[[1,2,3],[4,5,6]],create zeros_like(b) and ones_like(b). 

b=np.array([[1,2,3],[4,5,6]])
print("Zeros like b\n",np.zeros_like(b))
print("Ones like b\n",np.ones_like(b))

Zeros like b
 [[0 0 0]
 [0 0 0]]
Ones like b
 [[1 1 1]
 [1 1 1]]
