In [7]:
# Q1.Generate an array of 5 random float numbers between 0 and 1 using np.random.rand().

import numpy as np

rnum = np.random.rand(5)
print(rnum)

[0.45251132 0.7109512  0.67060188 0.5725487  0.52972705]


In [8]:
# Q2.Create a 2D random array (shape = 3x4) with random numbers between 0 and 1.

arr2d = np.random.rand(3, 4)
print(arr2d)

[[0.26134926 0.25798858 0.04363073 0.53361708]
 [0.76371435 0.49739723 0.62346432 0.00959039]
 [0.72411376 0.16041067 0.10615683 0.98377668]]


In [10]:
# Q3.Generate 10 random integers between 50 and 100 using np.random.randint().
rnum = np.random.randint(50, 101, size=10)
print(rnum)

[70 70 57 55 91 80 61 63 97 60]


In [11]:
# Q4.Create a 3x3 matrix of random integers between 1 and 9.

matrix = np.random.randint(1, 10, size=(3, 3))
print(matrix)

[[3 5 4]
 [1 1 1]
 [4 9 9]]


In [12]:
# Q5.Generate 5 random numbers from a normal distribution using np.random.randn().

num = np.random.randn(5)
print(num)

[ 0.53778633 -0.61117962 -1.84241417  0.37307485 -0.23616061]


In [21]:
# Q6.Use np.random.choice() to select 3 random elements from the array:

arr = np.array([10, 20, 30, 40, 50])
select = np.random.choice(arr, size=3, replace=False)
print(select)

[50 30 40]


In [22]:
# Q7.Use np.random.choice() to pick 5 elements with replacement from:

arr = np.array([1, 2, 3, 4, 5])
select = np.random.choice(arr, size=5, replace=True)
print(select)

[4 2 1 2 4]


In [23]:
# Q8.Shuffle this array using np.random.shuffle():

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 2 4 1 3]


In [25]:
# Q9.Generate two random arrays using the same np.random.seed(10) —check if both give the same result.
np.random.seed(10)
rand1 = np.random.rand(3)
np.random.seed(10)
rand2 = np.random.rand(3)
print("Array 1:", rand1)
print("Array 2:", rand2)

Array 1: [0.77132064 0.02075195 0.63364823]
Array 2: [0.77132064 0.02075195 0.63364823]


In [26]:
# Q10.

# Generate a 4x4 matrix of random integers between 10 and 99 and find:

# Maximum value

# Minimum value

# Mean

matrix = np.random.randint(10, 100, size=(4, 4))
max_value = np.max(matrix)
min_value = np.min(matrix)
mean_value = np.mean(matrix)
print("Matrix:\n", matrix)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Mean value:", mean_value)

Matrix:
 [[38 99 39 18]
 [83 10 50 46]
 [26 21 64 98]
 [72 43 82 88]]
Maximum value: 99
Minimum value: 10
Mean value: 54.8125
