In [2]:
# Dataset 1 — Students Marks

# marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])

# Q11: Find indexes of students who passed (marks ≥ 50).

# Q12: Replace all marks below 50 with 0 using np.where().

# Q13: Find where a new score 75 should be inserted to keep marks sorted.

# Q14: Get all scores greater than average marks.
import numpy as np

marks = np.array([35, 50, 65, 80, 40, 90, 55, 70])
avg = np.where(marks > 50)
print(avg)

rpl = np.where(marks<50, 0, marks)
print(rpl)

new = np.searchsorted(marks, 75)
print(new)

great = np.mean(marks)
greater = marks[marks>great]
print(great)
print(greater)

(array([2, 3, 5, 6, 7]),)
[ 0 50 65 80  0 90 55 70]
8
60.625
[65 80 90 70]


In [3]:
# 🧩 Dataset 2 — Product Prices

# prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])

# Q15: Find positions of products cheaper than ₹1000.

# Q16: Replace prices above ₹2000 with 'Expensive', others with 'Affordable'.

# Q17: Using np.searchsorted(), find where ₹1600 should be inserted to maintain order.

# Q18: Get all product prices between ₹1000 and ₹2000 using boolean indexing.

prices = np.array([1200, 800, 1500, 2500, 1800, 900, 3000])
cheap = np.where(prices>1000)
print(cheap)

pla = np.where(prices>2000, 'Expensive', 'Affordable')
print(pla)

price = np.searchsorted(prices, 1600)
print(price)

beet = np.where((prices>1000) & (prices<2000))
print(beet)

(array([0, 2, 3, 4, 6]),)
['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Affordable' 'Expensive']
3
(array([0, 2, 4]),)


In [4]:
# 🧩 Dataset 3 — City Temperatures (°C)

# temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])

# Q19: Find indexes of days where temperature > 35°C.

# Q20: Replace all temps > 35°C with 'Hot' and others with 'Normal'.

# Q21: Find where to insert a new temperature reading 33 to keep sorted order.

# Q22: Get all temperatures below average temperature.

temps = np.array([28, 34, 40, 25, 31, 38, 29, 41])
hot = np.where(temps>35)
print(hot)

rep = np.where(temps>35, 'Hot', 'Normal')
print(rep)

(array([2, 5, 7]),)
['Normal' 'Normal' 'Hot' 'Normal' 'Normal' 'Hot' 'Normal' 'Hot']


In [6]:
# 🧩 Dataset 4 — Employee Salaries

# salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

# Q23: Find indexes of employees earning more than ₹40,000.

# Q24: Replace salaries below ₹30,000 with 'Low', others with 'High'.

# Q25: Find where a new salary ₹50000 should be inserted in the sorted salary list.

# Q26: Get all salaries above the company average.

salaries = np.array([25000, 35000, 45000, 28000, 60000, 75000, 32000])

more = np.where(salaries>40000)
print(more)

replace = np.where(salaries<30000, 'Low', 'High')
print(replace)

find = np.searchsorted(salaries, 50000)
print(find)

avg = np.mean(salaries)
print(avg)

(array([2, 4, 5]),)
['Low' 'High' 'High' 'Low' 'High' 'High' 'High']
4
42857.142857142855


In [10]:
# 🧩 Dataset 5 — Daily Steps (Fitness Tracker)

# steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

# Q27: Find indexes of days with steps > 8000.

# Q28: Replace steps below 5000 with 'Low Activity' and others with 'Active'.

# Q29: Get all days where steps are below the weekly average.

# Q30: Check using np.any() if any day has 0 steps (missed logging).

steps = np.array([4000, 7500, 12000, 3000, 10000, 6000, 8000])

activate = np.where(steps > 8000)
print(activate)

replace = np.where(steps < 5000, 'Activity', 'Activate')
print(replace)

aver = steps.mean()
print(aver)

below_avg_days = np.where(steps < avg)[0]
below_avg_steps = steps[below_avg_days]
print(below_avg_days)
print(below_avg_steps)

zero = np.any(steps == 0)
print(zero)


(array([2, 4]),)
['Activity' 'Activate' 'Activate' 'Activity' 'Activate' 'Activate'
 'Activate']
7214.285714285715
[0 1 2 3 4 5 6]
[ 4000  7500 12000  3000 10000  6000  8000]
False
